### ISSUE TITLE
Test on Wild Image

### ISSUE THREAD

**Issue by josh-zhu** [dahiyaaneesh/peclr#2]
Hi, thanks for your nice work and sharing the pretrained model.  There are some questions that i am not so clear,  and hope for your reply.
Should i run the supervised training to get the final layer for testing,
 and how can i get the scale data on wild image?
Another question is regard to the augmentation: is it beneficial to try an extra segmentation augmentation？
Thanks.

**Comment by spurra** [comment]
Hi @josh-zhu , thank you for your interest in our work! Let me try and answer your questions:
1) You need to fine-tune the pre-trained networks on labeled data to get the final performance for testing. We fine-tuned on the FreiHAND dataset
2) We do not use scale information for the PeCLR pre-training. If you want scale information during downstream training, I'd advise to either use a MANO approach for fine-tuning, or go with the [2.5D approach](https://arxiv.org/abs/1804.09534) and estimate the scale by using an average.
3) Perhaps. It will depend on the details of the augmentation procedure.

Hope the answers help.

**Comment by josh-zhu** [comment]
Hi @spurra, thank you so much for your detailed answer. I will conduct experiments following your advice.
