### ISSUE TITLE
Will the finetune code be released?

### ISSUE THREAD

**Issue by deyingk** [dahiyaaneesh/peclr#6]
Hi Adrian,

Thanks for sharing your great work!

Will the code for finetuning the model on FreiHand be released? (Maybe I missed it somewhere.)

**Comment by spurra** [comment]
Hi deyingk, this is a joint first-author work between Aneesh Dahiya and me. 

The fine-tuning code will be released sometime in the future, but I cannot give an exact date as I'm currently on an internship.
