### ISSUE TITLE
Loss Weight to Train the RN_25D_wMLPref

### ISSUE THREAD

**Issue by fylwen** [dahiyaaneesh/peclr#9]
Hi, thanks for the released codes, and I have some questions related to the training of the 2.5D hand representation for hand pose estimation.

From the related papers, I consider that for the hand pose estimator the loss has three terms: 1) 2D pixel coordinate on the image plane, 2) the scale normalized relative z, and 3) the scale normalized z root (after refinement). I wonder whether my understanding is correct, and wonder about the value of weight parameters used to balance these three loss terms.

Thanks for your help!

**Comment by spurra** [comment]
Your understanding is correct! We use the same weights as explained in the supplementary of the following paper: https://arxiv.org/pdf/2003.09282.pdf (p.27)

i.e l_2d = 1, l_zrel = 5, l_zroot = 1
